name: autocommit-robot

on:
  schedule:
    - cron: "25 16 * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: DemonGao
          author_email: scgao94@gmail.com
          message: "feat: save robot"
          add: "pictures/*"

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
